import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ToastProvider from '@/app/contexts/ToastProvider';
import { AuthProvider } from '@/app/contexts/AuthContext';
import { ReservationProvider } from '@/app/contexts/ReservationContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-600 dark:text-gray-200`}
    >
    <AuthProvider>
      <ToastProvider>
        <ReservationProvider>{children}</ReservationProvider>
      </ToastProvider>
    </AuthProvider>
    </body>
    </html>
  );
}