import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/app/components/layout/header'
import HeaderMobile from '@/app/components/layout/headerMobile'
import MarginWidthWrapper from '@/app/components/layout/marginWidthWrapper'
import PageWrapper from '@/app/components/layout/pageWrapper'
import SideNav from '@/app/components/layout/sideNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Side Nav w/ Sub Menu',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`${inter.className}`}>
      <div className='flex'>
        <SideNav />
        <main className='flex-1'>
          <MarginWidthWrapper>
            <Header />
            <HeaderMobile />
            <PageWrapper>{children}</PageWrapper>
          </MarginWidthWrapper>
        </main>
      </div>
    </div>
  )
}
